package com.example.server.enums;

public enum NotificationType {
    NEW_PRICE_QUOTED,
    QUOTE_PRICE_ACCEPTED,
    QUOTE_PRICE_REJECTED,
    VOUCHER_APPROVED,
    VOUCHER_REJECTED,
    AMOUNT_CREDITED_TO_SELLER,
    VOUCHER_BOUGHT_SELLER,
    VOUCHER_BOUGHT_BUYER,
}
